version: '1'
networks:
    kafka-network:
     driver: bridge


services:

    zookeeper-server:
     image: 'bitnami/zookeeper:latest'
     networks:
       - kafka-network
     ports:
       - '2181:2181'
     environment:
       - ALLOW_ANONYMOUS_LOGIN=yes


    kafka-server1:
     image: 'bitnami/kafka:latest'
     networks:
        - kafka-network
     ports:
        - '9093:9093'
     environment:
        - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
        - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
        - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
        - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka-server1:9092,EXTERNAL://localhost:9093
        - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
        - ALLOW_PLAINTEXT_LISTENER=yes

     depends_on:
        - zookeeper-server


    kafka-server2:
      image: 'bitnami/kafka:latest'
      networks:
         - kafka-network
      ports:
         - '9094:9094'
      environment:
        - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
        - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
        - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
        - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka-server2:9092,EXTERNAL://localhost:9094
        - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9094
        - ALLOW_PLAINTEXT_LISTENER=yes

      depends_on:
         - zookeeper-server
